name: upi_chooser
description: Flutter plugin to get the list of UPI apps that are installed on the device.
version: 0.0.4
repository: https://github.com/cooltechie-info/upi-chooser
screenshots:
  - description: 'UPI App list'
    path: example/assets/img-upi-chooser.png

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  url_launcher: ^6.1.5
  appcheck: ^1.0.6
  android_intent_plus: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 
 
flutter:
  
  plugin:
    platforms:
      android:
        package: info.cooltechie.upi_chooser
        pluginClass: UpiChooserPlugin
      ios:
        pluginClass: UpiChooserPlugin
 
